#! /usr/bin/env bash

###############################################################################
# Monitor DB2 with Nagios
# Copyright 2013 Andres Gomez Casanova
# https://github.com/angoca/monitor-db2-with-nagios
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

# Checks the HADR status by looking if both databases are connected.
#
# Here comes the documentation
#
# # 'check_hadr_status' command definition
# define command {
#         command_name    check_hadr_status
#         command_line    $USER1$/check_by_ssh -H $HOSTADDRESS$ -l nagios -t 20 -C "scripts/check_hadr_status -i '$ARG1$' -d '$ARG2$'"
# }
# define service{
#         host_name               db2server
#         service_description     HADR status
#         check_command           check_hadr_status!/home/db2inst1!sample
#         use                     generic-service
# }
#
# Parameters:
# -d | --database : Database name.
# -h | --help : Show the help of this script.
# -i | --instance : Home directory of the instance. Usually it is
#   /home/db2inst1
# -V | --version : Show the current version of this script.
# -v | --verbose : Execute the program in verbose mode.
#
# The exit codes are the standard for Nagios.
#
# 0 The plugin was able to check the service and it appeared to be functioning
#   properly.
# 1 The plugin was able to check the service, but it appeared to be above some
#   "warning" threshold or did not appear to be working properly.
# 2 The plugin detected that either the service was not running or it was above
#   some "critical" threshold.
# 3 Invalid command line arguments were supplied to the plugin or low-level
#   failures internal to the plugin (such as unable to fork, or open a tcp
#   socket) that prevent it from performing the specified operation.
#   Higher-level errors (such as name resolution errors, socket timeouts, etc)
#   are outside of the control of plugins and should generally NOT be reported
#   as UNKNOWN states.
#
# Author: Andres Gomez Casanova
# Version: v1.0 2013-01-18

# Flag for debugging.
#set -xv

# Version of this script.
function print_revision {
  echo Andres Gomez Casanova - AngocA
  echo v1.0 2013-02-07
}
# Function to show the help
function print_usage {
  echo "Usage: $1 { -i instanceHomeDirectory -d databaseName # -h # -V } [ -v ]"
}

function print_help {
  print_revision
  print_usage $1
  # Max 80 chars width.
  /bin/cat <<__EOT
Checks the HADR status of the database.
-d | --database STRING
   Database name.
-h | --help
   Shows the current documentation.
-i | --instance STRING
   Instance home directory. It is usually /home/db2inst1
-v | --verbose
   Executes the script in verbose mode (multiple times).
-V | --version
   Shows the current version of this script.
__EOT
}

# Variable to control the flow execution. Prevent Spaghetti code.
CONTINUE=true

# Nagios return codes
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
# This is the returned code.
RETURN=$UNKNOWN

# Nagios Output
# Text output 80 chars | Optional Perf Data Line 1
# Long text Line 1
# Long text Line 2 | Optional Perf Data Line 2
# Optional Perf Data Line 3
OUTPUT=
PERFORMANCE=
LONG_OUTPUT=
LONG_PERFORMANCE=

APPL_NAME=$0

if [[ $# -eq 0 ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

# The following requieres GNU getopt. See the following discusion.
# http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options

TEMP=`getopt -o hVvi:d: --long help,version,verbose,instance:,database: \
             -n $APPL_NAME -- "$@"`

if [[ $? -ne 0 ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true ]] ; then
  # Note the quotes around $TEMP: they are essential!
  eval set -- "$TEMP"

  HELP=false
  VERSION=false
  # Verbosity level
  VERBOSE=0
  INSTANCE_HOME=
  DATABASE_NAME=
  while true; do
    case "$1" in
      -d | --database ) DATABASE_NAME=`echo $2 | awk '{print $1}'`; shift 2 ;;
      -h | --help ) HELP=true; shift ;;
      -i | --instance ) INSTANCE_HOME=`echo $2 | awk '{print $1}'`; shift 2 ;;
      -V | --version ) VERSION=true; shift ;;
      -v | --verbose ) VERBOSE=$VERBOSE+1; shift ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done
fi

if [[ $VERBOSE -ge 2 ]] ; then
  ECHO="help:$HELP, version:$VERSION, verbose:$VERBOSE, "
  ECHO=$ECHO"directory:$INSTANCE_HOME, database:$DATABASE_NAME "
  echo $ECHO
fi

if [[ $CONTINUE == true && $HELP == true ]] ; then
  print_help $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true && $VERSION == true ]] ; then
  print_revision $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true && $INSTANCE_HOME == "" ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true && $DATABASE_NAME == "" ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true ]] ; then
  # Trims the characters.
  INSTANCE_HOME=`echo $INSTANCE_HOME | awk '{print $1}'`
  DATABASE_NAME=`echo $DATABASE_NAME | awk '{print $1}'`

  if [[ -d $INSTANCE_HOME && -e $INSTANCE_HOME/sqllib/db2profile ]] ; then
    # Load the DB2 profile.
    . $INSTANCE_HOME/sqllib/db2profile
  else
    OUTPUT="Instance directory is invalid."
    RETURN=$UNKNOWN
    CONTINUE=false
  fi
fi

if [[ $CONTINUE == true ]] ; then
  COMMAND_DATABASE="db2 list db directory"
  if [[ $VERBOSE -ge 2 ]] ; then
    echo "COMMAND: $COMMAND_DATABASE"
  fi
  DATABASE=`$COMMAND_DATABASE | awk '/Database alias/ {print $4}' | grep -iw $DATABASE_NAME`
  if [[ $VERBOSE -ge 3 ]] ; then
    echo "RESULT:'$DATABASE'"
  fi

  if [[ $DATABASE == "" ]] ; then
    OUTPUT="The database $DATABASE_NAME is not cataloged."
    RETURN=$UNKNOWN
    CONTINUE=false
  fi
fi

if [[ $CONTINUE == true ]] ; then
  COMMAND_ROLE="db2 get db cfg for $DATABASE_NAME"
  if [[ $VERBOSE -ge 2 ]] ; then
    echo "COMMAND: $COMMAND_ROLE"
  fi
  ROLE=`$COMMAND_ROLE | awk '/HADR database role/ {print $5}'`
  if [[ $VERBOSE -ge 3 ]] ; then
    echo "RESULT:'$ROLE'"
  fi
  if [[ $ROLE == "STANDARD" ]] ; then
    OUTPUT="Database is not in HADR"
    RETURN=$UNKNOWN
  else
    if [[ $ROLE == "PRIMARY" ]] ; then
      COMMAND_PRIMARY="db2pd -db wfscpd -hadr"
      if [[ $VERBOSE -ge 2 ]] ; then
        echo "COMMAND: $COMMAND_PRIMARY"
      fi
      PRIMARY=`$COMMAND_PRIMARY | awk '/^Primary / {print $2}'`
      if [[ $VERBOSE -ge 3 ]] ; then
        echo "RESULT:'$PRIMARY'"
      fi
      if [[ $PRIMARY == "Peer" ]] ; then
        OUTPUT="Database is primary and peer"
        RETURN=$OK
      elif [[ $PRIMARY == "Disconnected" ]] ; then
        OUTPUT="Standby database is not reachable"
        RETURN=$CRITICAL
      else
        OUTPUT="Database is primary and not peer: $PRIMARY"
        RETURN=$UNKNOWN
      fi
    elif [[ $ROLE == "STANDBY" ]] ; then
      COMMAND_STANDBY="db2pd -db wfscpd -hadr"
      if [[ $VERBOSE -ge 2 ]] ; then
        echo "COMMAND: $COMMAND_STANDBY"
      fi
      STANDBY=`$COMMAND_STANDBY | awk '/^Standby/ {print $2}'`
      if [[ $VERBOSE -ge 3 ]] ; then
        echo "RESULT:'$STANDBY'"
      fi
      if [[ $STANDBY == "Peer" ]] ; then
        OUTPUT="Database is standby and peer"
        RETURN=$OK
      elif [[ $STANDBY == "DisconnectedPeer" ]] ; then
        OUTPUT="Pimary database is not reachable"
        RETURN=$CRITICAL
      else
        OUTPUT="Database is standby and not peer: $STANDBY"
        RETURN=$UNKNOWN
      fi
    else
      OUTPUT="Database role is unknown ($ROLE)"
      RETURN=$UNKNOWN
      CONTINUE=false
    fi
  fi
fi
if [[ $CONTINUE == true ]] ; then
  HEX_DIFF=`db2pd -db wfscpd -hadr | awk '/LOG/ {print $3}' | awk -Fx '{print $2}' | sed 'N;s/\n/-/' | awk '{print "ibase=16;"$1}' | bc`
  PERFORMANCE="HexDiff=${HEX_DIFF} " 
  PAGE_DIFF=`db2pd -db wfscpd -hadr | awk '/LOG/ {print $2}' | sed 'N;s/\n/-/' | bc`
  LOG_DIFF=`db2pd -db wfscpd -hadr | awk '/LOG/ {print $1}' | awk -F. '{print $1}' | sed 's/^.//' | sed 'N;s/\n/-/' | bc`
  LONG_PERFORMANCE="PageDiff=${PAGE_DIFF} LogDiff=${LOG_DIFF} " 
fi
# Prints the output.
if [[ $OUTPUT == "" ]] ; then
  OUTPUT="Note: The test was not executed."
fi
# Builds the output.
echo "$OUTPUT|$PERFORMANCE
$LONG_OUTPUT|$LONG_PERFORMANCE"
# Returns the error code.
if [[ $VERBOSE -ge 2 ]] ; then
  echo "Return code: $RETURN"
fi
exit $RETURN
