#! /usr/bin/env bash

###############################################################################
# Monitor DB2 with Nagios
# Copyright 2013,2014,2015 Andres Gomez Casanova
# https://github.com/angoca/monitor-db2-with-nagios
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

# Check the quantity of messages written in the db2diag.log file. It allows to
# detect an abnormal behaviour in the instance, because most of the time, when
# an recurrent error happens in the database/instance, it is described in the
# diagnostic file.
#
# Here comes the documentation
#
# In order to be used in Nagios, you have to configure the following.
#
# 'check_db2diag' command definition
# define command {
#         command_name    check_db2diag
#         command_line    $USER1$/check_by_ssh -H $HOSTADDRESS$ -l nagios -C "scripts/check_db2diag -i '$ARG1$'"
# }
# define service{
#         host_name               db2server
#         service_description     Diagnostic messages
#         check_command           check_db2diag!/home/db2inst1
#         use                     generic-service
# }
#
# When using NRPE:
#
# In the database server:
#
# command[check_db2diag]=/home/nagios/scripts/check_db2diag -i /home/db2inst1
#
# Then modify the path according to your script location, instance home dir,
# database and thresholds.
#
# In the Nagios server:
#
# define service{
#         host_name               db2server
#         service_description     Diagnostic messages
#         check_command           check_nrpe_1arg!check_db2diag
#         use                     generic-service
# }
#
# Parameters:
# -c | --critical : Quantity of messages produced to be considered as critical.
#    Default 40 between two calls.
# -d | --database : Database name.
# -h | --help : Show the help of this script.
# -i | --instance : Home directory of the instance. Usually it is
#   /home/db2inst1.
# -K | --mk : Change the output for Check_MK.
# -R | --noreplace : Do not replace the last written date. This allows you to
#   execute the script without altering the date.
# -T | --trace : Trace mode. Writes output in /tmp.
# -v | --verbose : Execute the program in verbose mode.
# -V | --version : Show the current version of this script.
# -w | --warning : Quantity of messages written in the db2diag.log file to be
#    considered as critical. Default 20 between to calls.
# -x | --extra : Shows extra information for the performance values.
#
# In AIX, the long name options are not supported.
#
# The exit codes are the standard for Nagios.
#
# 0 The plugin was able to check the service and it appeared to be functioning
#   properly.
# 1 The plugin was able to check the service, but it appeared to be above some
#   "warning" threshold or did not appear to be working properly.
# 2 The plugin detected that either the service was not running or it was above
#   some "critical" threshold.
# 3 Invalid command line arguments were supplied to the plugin or low-level
#   failures internal to the plugin (such as unable to fork, or open a tcp
#   socket) that prevent it from performing the specified operation.
#   Higher-level errors (such as name resolution errors, socket timeouts, etc)
#   are outside of the control of plugins and should generally NOT be reported
#   as UNKNOWN states.
#
# Author: Andres Gomez Casanova
# Version: v1.1 2015-10-15

# Flag for debugging.
#set -xv

# Locale to print messages in English. Prevent language problems.
export LANG=en_US

# Version of this script.
function print_revision {
  echo Andres Gomez Casanova - AngocA
  echo v1.1 2015-10-15
}
# Function to show the help
function print_usage {
  /bin/cat <<__EOT
Usage: ${1} { -i instanceHomeDirectory [-c][-w][-K][-R][-x] | -h | -V }
[-T][-v]
__EOT
}

function print_help {
  print_revision
  print_usage ${1}
  # Max 80 chars width.
  /bin/cat <<__EOT
-------------------------------------------------------------------------------
Checks the quantity of messages written in the db2diag.log since the last
check.
-c | --critical INTEGER
   Quantity of messages to be considered as critical. Default 40 between calls.
-h | --help
   Shows the current documentation.
-i | --instance STRING
   Instance home directory. It is usually /home/db2inst1.
-K | --mk
   Changes the output to be compatible with Check_MK.
-R | --noreplace
   Do not replace the last check time of the plugin. This allows to execute the
   script without altering other executions.
-T | --trace
   Trace mode: writes date and output in /tmp.
-v | --verbose
   Executes the script in verbose mode (multiple times).
-V | --version
   Shows the current version of this script.
-w | --warning INTEGER
   Quantity of messages to be considered as warning. Default 20 between calls.
-x | --extra
   Shows extra information for the performance values.

In AIX, the long name options are not supported.
__EOT
}

# Variable to control the flow execution. Prevent Spaghetti code.
CONTINUE=true

# Nagios return codes
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
# This is the returned code.
RETURN=${UNKNOWN}

# Nagios Output
# Text output 80 chars | Optional Perf Data Line 1
# Long text Line 1
# Long text Line 2 | Optional Perf Data Line 2
# Optional Perf Data Line 3
OUTPUT=
PERFORMANCE=
LONG_OUTPUT=
LONG_PERFORMANCE=
PERF_MK="-"

APPL_NAME=$(basename ${0})

echo "$(date +"%Y-%m-%d-%H.%M.%S") $$ Started ${APPL_NAME} $@" >> /tmp/${APPL_NAME}.log

# Checks the lock file does not exist.
# The lock file is the way the command was called with its parameters
# without spaces.
COPY_ARGS=("${@}") 
LOCK_FILE=
for VALUE in "${COPY_ARGS[@]}" ; do
  LOCK_FILE="${LOCK_FILE}${VALUE}"
done
LOCK_FILE=${LOCK_FILE//\//}
LOCK_FILE=${LOCK_FILE//\\/}
LOCK_FILE=${LOCK_FILE//\:/}
LOCK_FILE=${LOCK_FILE//\*/}
LOCK_FILE=${LOCK_FILE//\|/}
LOCK_FILE="/tmp/${APPL_NAME}${LOCK_FILE}.lock"
if [[ ! -r ${LOCK_FILE} ]] ; then
  echo $$ > ${LOCK_FILE}
  LOCKED=true
else
  # If it exist, then check if the process is running.
  EXIST=$(ps -ef | grep $(cat ${LOCK_FILE}) | grep ${APPL_NAME})
  # If process is not running, delete it.
  if [[ ${EXIST} == "" ]] ; then
    rm ${LOCK_FILE}
    if [[ ! -r ${LOCK_FILE} ]] ; then
      echo $$ > ${LOCK_FILE}
      LOCKED=true
    else
      OUTPUT="The lock file cannot be replaced: ${LOCK_FILE}"
      CONTINUE=false
      RETURN=${UNKNOWN}
    fi
  else
    OUTPUT="An instance of the script with the same parameters is already running."
    CONTINUE=false
    RETURN=${UNKNOWN}
  fi
fi

if [[ ${#} -eq 0 ]] ; then
  print_usage ${APPL_NAME}
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

# Checks the operating system. geopt works different in AIX than in Linux.
OS=$(uname)

if [[ "${OS:0:5}" == "Linux" ]] ; then
  # The following requires GNU getopt. See the following discussion.
  # http://stackoverflow.com/questions/402377

  TEMP=$(getopt -o c:hi:KRTvVw:x --long critical:,extra,help,instance:,mk,noreplace,trace,verbose,version,warning: \
               -n ${APPL_NAME} -- "${@}")
elif [[ "${OS:0:3}" == "AIX" ]] ; then
  set -- $(getopt c:hi:KRTvVw:x ${*})
elif [[ "${OS:0:6}" == "Darwin" || "${OS:0:5}" == "SunOS" || "${OS:0:5}" == "HP-UX" ]] ; then
  echo "This plugin is not yet supported in your platform."
  echo "Please create a ticket in GitHub if you want to enable your current platform."
  echo "https://github.com/angoca/monitor-db2-with-nagios/issues"
  RETURN=${UNKNOWN}
  CONTINUE=false
elif [[ "${OS:0:6}" == "CYGWIN" ]] ; then
  echo "This plugin is not supported in Cygwin"
  RETURN=${UNKNOWN}
  CONTINUE=false
else
  echo "The platform is unknown: ${OS}"
  echo "Please create a ticket in GitHub: https://github.com/angoca/monitor-db2-with-nagios/issues"
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

if [[ ${?} -ne 0 ]] ; then
  print_usage ${APPL_NAME}
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

if [[ ${CONTINUE} == true ]] ; then
  if [[ "${OS}" == "Linux" ]] ; then
    # Note the quotes around ${TEMP}: they are essential!
    eval set -- "${TEMP}"
  fi

  HELP=false
  VERSION=false
  CHECK_MK=false
  # Verbosity level
  VERBOSE=0
  # Trace activated
  TRACE=false
  # Replace date.
  REPLACE=true
  EXTRA=false
  LOG=/tmp/${APPL_NAME}.log
  INSTANCE_HOME=
  WARNING_THRES=20
  CRITICAL_THRES=40
  if [[ "${OS:0:5}" == "Linux" ]] ; then
    while true; do
      case "${1}" in
        -c | --critical ) CRITICAL_THRES=$(echo ${2} | cut -d' ' -f1) ; shift 2 ;;
        -h | --help ) HELP=true ; shift ;;
        -i | --instance ) INSTANCE_HOME=$(echo ${2} | cut -d' ' -f1) ; shift 2 ;;
        -K | --mk ) CHECK_MK=true ; shift ;;
        -R | --noreplace ) REPLACE=false ; shift ;;
        -T | --trace ) TRACE=true ; shift ;;
        -v | --verbose ) VERBOSE=$(( ${VERBOSE} + 1 )) ; shift ;;
        -V | --version ) VERSION=true ; shift ;;
        -w | --warning ) WARNING_THRES=$(echo ${2} | cut -d' ' -f1) ; shift 2 ;;
        -x | --extra ) EXTRA=true ; shift ;;
        -- ) shift ; break ;;
        * ) break ;;
      esac
    done
  elif [[ "${OS:0:3}" = "AIX" ]] ; then
    while [[ $1 != -- ]] ; do
      case "${1}" in
        -c) CRITICAL_THRES=$(echo ${2} | cut -d' ' -f1) ; shift 2 ;;
        -h) HELP=true ; shift ;;
        -i) INSTANCE_HOME=$(echo ${2} | cut -d' ' -f1) ; shift 2 ;;
        -K) CHECK_MK=true ; shift ;;
        -R) REPLACE=false ; shift ;;
        -T) TRACE=true ; shift ;;
        -v) VERBOSE=$(( ${VERBOSE} + 1 )) ; shift ;;
        -V) VERSION=true ; shift ;;
        -w) WARNING_THRES=$(echo ${2} | cut -d' ' -f1) ; shift 2 ;;
        -x) EXTRA=true ; shift ;;
        * ) break ;;
      esac
    done
  fi
fi

if [[ ${TRACE} == true ]] ; then
  echo ">>>>>" >> ${LOG}
  date >> ${LOG}
  echo "Instance at ${INSTANCE_HOME}" >> ${LOG}
  echo "PID ${$}" >> ${LOG}
fi

ECHO="help:${HELP}, version:${VERSION}, verbose:${VERBOSE}"
ECHO="${ECHO}, directory:${INSTANCE_HOME}, extra: ${EXTRA}"
ECHO="${ECHO}, warning:${WARNING_THRES}, critical:${CRITICAL_THRES}"
ECHO="${ECHO}, replace:${REPLACE}, check_mk:${CHECK_MK}"

if [[ ${VERBOSE} -ge 2 ]] ; then
  echo ${ECHO}
fi

if [[ ${TRACE} == true ]] ; then
  echo "PARAMS:${ECHO}" >> ${LOG}
fi

if [[ ${CONTINUE} == true && ${HELP} == true ]] ; then
  print_help ${APPL_NAME}
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

if [[ ${CONTINUE} == true && ${VERSION} == true ]] ; then
  print_revision ${APPL_NAME}
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

if [[ ${CONTINUE} == true && ${INSTANCE_HOME} == "" ]] ; then
  print_usage ${APPL_NAME}
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

if [[ ${CONTINUE} == true
    && ( ${WARNING_THRES} == "" || ${CRITICAL_THRES} == ""
    || ! ${WARNING_THRES} =~ ^[0-9]+$ || ! ${CRITICAL_THRES} =~ ^[0-9]+$
    || ${WARNING_THRES} -le 0 || ${CRITICAL_THRES} -le 0
    || ${WARNING_THRES} -ge ${CRITICAL_THRES} ) ]] ; then
  print_usage ${APPL_NAME}
  echo "Warning threshold should be less than critical threshold."
  echo "Threshold should be greater than 0."
  RETURN=${UNKNOWN}
  CONTINUE=false
fi

if [[ ${CONTINUE} == true ]] ; then
  if [[ -d ${INSTANCE_HOME} && -e ${INSTANCE_HOME}/sqllib/db2profile ]] ; then
    # Load the DB2 profile.
    . ${INSTANCE_HOME}/sqllib/db2profile
    INSTANCE_NAME=$(db2 get instance | awk '/instance/ {print $7}')
  else
    OUTPUT="Instance directory is invalid."
    RETURN=${UNKNOWN}
    CONTINUE=false
  fi
fi

if [[ ${CONTINUE} == true ]] ; then
  DATE_FILE=/tmp/last_date_check_db2diag_${INSTANCE_NAME}
  # Checks if the file can be read
  if [[ -r ${DATE_FILE} ]] ; then
    # Counts the blank lines base on the read date.
    DATE_VALUE=$(cat ${DATE_FILE})
    COMMAND_QTY="db2diag -readfile -time ${DATE_VALUE}"
    if [[ ${VERBOSE} -ge 2 ]] ; then
      echo "COMMAND: ${COMMAND_QTY}"
      echo " | grep -cv '\S'"
    fi
    QTY=$(${COMMAND_QTY} | grep -cv '\S')
    if [[ ${VERBOSE} -ge 3 ]] ; then
      echo "Result: ${QTY}"
    fi

    # Checks for a valid output.
    RE='^[0-9]+$'
    if [[ ! ${QTY} =~ ${RE} ]] ; then
      OUTPUT="Output is not a number: '${QTY}'"
      RETURN=${UNKNOWN}
    else
      # Checks the value with the thresholds.
      if [[ ${QTY} -lt ${WARNING_THRES} ]] ; then
        OUTPUT="OK, quantity is normal (${QTY}) since ${DATE_VALUE}."
        RETURN=${OK}
      elif [[ ${QTY} -lt ${CRITICAL_THRES} ]] ; then
        OUTPUT="Quantity is increasing (${QTY}) since ${DATE_VALUE}, please check the db2diag.log."
        RETURN=${WARNING}
      else
        OUTPUT="Quantity is too high (${QTY}) since ${DATE_VALUE}, please check the db2diag.log right now."
        RETURN=${CRITICAL}
      fi
      # Calculates the performance values (for each level)
      PERFORMANCE="'logs'=${QTY};${WARNING_THRES};${CRITICAL_THRES}"
      if [[ ${QTY} -lt $((3 * ${CRITICAL_THRES})) ]] ; then
        COMMAND_QTY_SEVERE="db2diag -readfile -time ${DATE_VALUE} -l Severe"
        COMMAND_QTY_CRITICAL="db2diag -readfile -time ${DATE_VALUE} -l Critical"
        COMMAND_QTY_ERROR="db2diag -readfile -time ${DATE_VALUE} -l Error"
        COMMAND_QTY_WARNING="db2diag -readfile -time ${DATE_VALUE} -l Warning"
        COMMAND_QTY_INFO="db2diag -readfile -time ${DATE_VALUE} -l Info"
        COMMAND_QTY_EVENT="db2diag -readfile -time ${DATE_VALUE} -l Event"
        if [[ ${VERBOSE} -ge 2 ]] ; then
          echo "COMMAND SEVERE: ${COMMAND_QTY_SEVERE}"
          echo "COMMAND CRITICAL: ${COMMAND_QTY_CRITICAL}"
          echo "COMMAND ERROR: ${COMMAND_QTY_ERROR}"
          echo "COMMAND WARNING: ${COMMAND_QTY_WARNING}"
          echo "COMMAND INFO: ${COMMAND_QTY_INFO}"
          echo "COMMAND EVENT: ${COMMAND_QTY_EVENT}"
        fi
        QTY_SEVERE=$(${COMMAND_QTY_SEVERE} | grep -cv '\S')
        QTY_CRITICAL=$(${COMMAND_QTY_CRITICAL} | grep -cv '\S')
        QTY_ERROR=$(${COMMAND_QTY_ERROR} | grep -cv '\S')
        QTY_WARNING=$(${COMMAND_QTY_WARNING} | grep -cv '\S')
        QTY_INFO=$(${COMMAND_QTY_INFO} | grep -cv '\S')
        QTY_EVENT=$(${COMMAND_QTY_EVENT} | grep -cv '\S')
        if [[ ${EXTRA} == true ]] ; then
          QTY_LINES=$(${COMMAND_QTY} | wc -l)
          QTY_CHARS=$(${COMMAND_QTY} | wc -m)
        fi
        if [[ ${VERBOSE} -ge 3 ]] ; then
          echo "Result: ${QTY_SEVERE}"
          echo "Result: ${QTY_CRITICAL}"
          echo "Result: ${QTY_ERROR}"
          echo "Result: ${QTY_WARNING}"
          echo "Result: ${QTY_INFO}"
          echo "Result: ${QTY_EVENT}"
          echo "Result: ${QTY_LINES}"
          echo "Result: ${QTY_CHARS}"
        fi
        LONG_OUTPUT="Messages by levels. Severe: ${QTY_SEVERE}, Critical: ${QTY_CRITICAL}, Error: ${QTY_ERROR}, Warning: ${QTY_WARNING}, Info: ${QTY_INFO}, Event: ${QTY_EVENT}"
        LONG_PERFORMANCE="'Severe'=${QTY_SEVERE}\n'Critical'=${QTY_CRITICAL}\n'Error'=${QTY_ERROR}\n'Warning'=${QTY_WARNING}\n'Info'=${QTY_INFO}\n'Event'=${QTY_EVENT}"
        PERF_MK="${PERFORMANCE}|'Msg_Severe'=${QTY_SEVERE}|'Msg_Critical'=${QTY_CRITICAL}|'Msg_Error'=${QTY_ERROR}|'Msg_Warning'=${QTY_WARNING}|'Msg_Info'=${QTY_INFO}|'Msg_Event'=${QTY_EVENT}"
        if [[ ${EXTRA} == true ]] ; then
          QTY_CHAR_K=$((${QTY_CHARS}/1024))
          LONG_OUTPUT="${LONG_OUTPUT}, Lines: ${QTY_LINES}, Size: ${QTY_CHAR_K}"
          LONG_PERFORMANCE="${LONG_PERFORMANCE}\n'Lines'=${QTY_LINES}\n'Size'=${QTY_CHAR_K}"
          PERF_MK="${PERF_MK}|'Lines'=${QTY_LINES}|'Size'=${QTY_CHAR_K}"
        fi
      fi
      # Writes the new date in the same file.
      if [[ ${REPLACE} == true ]] ; then
        if [[ -w ${DATE_FILE} ]] ; then
          date +"%Y-%m-%d-%H.%M.%S" > ${DATE_FILE}
        else
          OUTPUT="File permissions are wrong '${DATE_FILE}'. ${OUTPUT}"
          RETURN=${CRITICAL}
        fi
      fi
    fi
  else
    # This is the first execution, thus a reference point for the date does not
    # exist.
    OUTPUT="First execution, there is not a reference point."
    RETURN=${UNKNOWN}
    touch ${DATE_FILE}
    chmod 666 ${DATE_FILE} 2> /dev/null
    if [[ -w ${DATE_FILE} ]] ; then
      date +"%Y-%m-%d-%H.%M.%S" > ${DATE_FILE}
    else
      OUTPUT="File permissions are wrong '${DATE_FILE}'. ${OUTPUT}"
    fi
  fi
fi

# Prints the output.
if [[ ${OUTPUT} == "" ]] ; then
  OUTPUT="Note: The test was not executed."
fi
# Builds the output.
if [[ ${CHECK_MK} == true ]] ; then
  echo "${RETURN} db2diagMsgs-${INSTANCE_NAME} ${PERF_MK} ${OUTPUT}"
else
  echo -e "${OUTPUT}|${PERFORMANCE}\n${LONG_OUTPUT}|${LONG_PERFORMANCE}"
fi
# Returns the error code.
if [[ ${VERBOSE} -ge 2 ]] ; then
  echo "Return code: ${RETURN}"
fi
if [[ ${TRACE} == true ]] ; then
  echo -e "OUTPUT:${OUTPUT}\nPERF:${PERFORMANCE}\nLONG_OUT:${LONG_OUTPUT}\nLONGPERF:${LONG_PERFORMANCE}\nRET_CODE:${RETURN}" >> ${LOG}
  date >> ${LOG}
  echo -e "<<<<<\n" >> ${LOG}
fi

if [[ ${LOCKED} == true && -r ${LOCK_FILE} ]] ; then
  rm ${LOCK_FILE}
fi

echo "$(date +"%Y-%m-%d-%H.%M.%S") $$ Ended ${APPL_NAME} ${COPY_ARGS[@]}" >> /tmp/${APPL_NAME}.log

exit ${RETURN}

