#! /usr/bin/env bash

###############################################################################
# Monitor DB2 with Nagios
# Copyright 2013 Andres Gomez Casanova
# https://github.com/angoca/monitor-db2-with-nagios
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

# Checks the memory usage by an instance. It does not take into account the
# bufferpools, or other memory dumps, it just takes the result of the query.
# The query is executed agaist the first connectable database of an instance.
#
# Here comes the documentation
#
# TODO Nagios usage.
#
# TODO Nagios with NRPE.
#
# Parameters:
# -c | --critical : Quantity of used memory to be considered as critical.
# -h | --help : Show the help of this script.
# -i | --instance : Home directory of the instance. Usually it is
#   /home/db2inst1
# -l | --limit : Memory limit. If nothing, the script always returns OK.
# -T | --trace : Trace mode. Writes output in /tmp
# -v | --verbose : Execute the program in verbose mode.
# -V | --version : Show the current version of this script.
# -w | --warning : Quantity of used memory to be considered as critical.
#
# The exit codes are the standard for Nagios.
#
# 0 The plugin was able to check the service and it appeared to be functioning
#   properly.
# 1 The plugin was able to check the service, but it appeared to be above some
#   "warning" threshold or did not appear to be working properly.
# 2 The plugin detected that either the service was not running or it was above
#   some "critical" threshold.
# 3 Invalid command line arguments were supplied to the plugin or low-level
#   failures internal to the plugin (such as unable to fork, or open a tcp
#   socket) that prevent it from performing the specified operation.
#   Higher-level errors (such as name resolution errors, socket timeouts, etc)
#   are outside of the control of plugins and should generally NOT be reported
#   as UNKNOWN states.
#
# Author: Andres Gomez Casanova
# Version: v1.0 2013-05-26

# Flag for debugging.
#set -xv

# Locale to print messages in English. Prevent language problems.
export LANG=en_US

# Version of this script.
function print_revision {
  echo Andres Gomez Casanova - AngocA
  echo v1.0 2013-05-26
}
# Function to show the help
function print_usage {
  echo "Usage: $1 { -i instanceHomeDirectory [-l][-c][-w] ! -h ! -V } \
[-T]\n [-v]"
}

function print_help {
  print_revision
  print_usage $1
  # Max 80 chars width.
  /bin/cat <<__EOT
Checks the memory usage at an instance (all nodes).
-c | --critical INTEGER
   Quantity of memory considered as critical. Limit option should be active.
-h | --help
   Shows the current documentation.
-i | --instance STRING
   Instance home directory. It is usually /home/db2inst1
-l | --limit
   Check the usage with a given limit (thresholds). If this option is not
   given, the script always returns OK.
-T | --trace
   Trace mode: writes date and output in /tmp
-v | --verbose
   Executes the script in verbose mode (multiple times).
-V | --version
   Shows the current version of this script.
-w | --warning INTEGER
   Quantity of memory considered as warning. Limit option should be active.
__EOT
}

# Variable to control the flow execution. Prevent Spaghetti code.
CONTINUE=true

# Nagios return codes
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
# This is the returned code.
RETURN=$UNKNOWN

# Nagios Output
# Text output 80 chars | Optional Perf Data Line 1
# Long text Line 1
# Long text Line 2 | Optional Perf Data Line 2
# Optional Perf Data Line 3
OUTPUT=
PERFORMANCE=
LONG_OUTPUT=
LONG_PERFORMANCE=

APPL_NAME=$(basename ${0})

if [[ $# -eq 0 ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

# The following requieres GNU getopt. See the following discusion.
# http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options

TEMP=$(getopt -o c:hi:ilTvVw: --long critical:,instance:,help,limit,trace,verbose,version,warning: \
             -n $APPL_NAME -- "$@")

if [[ $? -ne 0 ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true ]] ; then
  # Note the quotes around $TEMP: they are essential!
  eval set -- "$TEMP"

  HELP=false
  VERSION=false
  # Verbosity level
  VERBOSE=0
  # Trace activated
  TRACE=false
  LOG=/tmp/${APPL_NAME}.log
  INSTANCE_HOME=
  LIMIT=false
  WARNING_THRES=1
  CRITICAL_THRES=2
  while true; do
    case "$1" in
      -c | --critical ) CRITICAL_THRES=$(echo $2 | cut -d' ' -f1) ; shift 2 ;;
      -h | --help ) HELP=true; shift ;;
      -i | --instance ) INSTANCE_HOME=$(echo $2 | cut -d' ' -f1) ; shift 2 ;;
      -l | --limit ) LIMIT=true ; shift ;;
      -T | --trace ) TRACE=true ; shift ;;
      -V | --version ) VERSION=true; shift ;;
      -v | --verbose ) VERBOSE=$(( $VERBOSE + 1 )); shift ;;
      -w | --warning ) WARNING_THRES=$(echo $2 | cut -d' ' -f1) ; shift 2 ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done
fi

if [[ $TRACE == true ]] ; then
  echo ">>>>>" >> $LOG
  date >> $LOG
  echo "PID $$" >> $LOG
fi

ECHO="help:${HELP}, version:${VERSION}, verbose:${VERBOSE}"
ECHO="${ECHO}, directory:${INSTANCE_HOME}, limit:${LIMIT}"
ECHO="${ECHO}, warning:${WARNING_THRES}, critical:${CRITICAL_THRES}"

if [[ $VERBOSE -ge 2 ]] ; then
  echo $ECHO
fi
if [[ $TRACE == true ]] ; then
  echo "PARAMS:$ECHO" >> $LOG
fi

if [[ $CONTINUE == true && $HELP == true ]] ; then
  print_help $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true && $VERSION == true ]] ; then
  print_revision $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true && $INSTANCE_HOME == "" ]] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true && ( $WARNING_THRES == "" || $CRITICAL_THRES == ""
    || ! $WARNING_THRES =~ ^[0-9]+$ || ! $CRITICAL_THRES =~ ^[0-9]+$
    || $WARNING_THRES -le 0 || $CRITICAL_THRES -le 0
    || $WARNING_THRES -ge $CRITICAL_THRES ) ]] ; then
  print_usage $APPL_NAME
  echo "Warning threshold should be less than critical threshold."
  echo "Threshold should be greater than 0."
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true ]] ; then
  if [[ -d $INSTANCE_HOME && -e $INSTANCE_HOME/sqllib/db2profile ]] ; then
    # Load the DB2 profile.
    . $INSTANCE_HOME/sqllib/db2profile
  else
    OUTPUT="Instance directory is invalid."
    RETURN=$UNKNOWN
    CONTINUE=false
  fi
fi

if [[ $CONTINUE == true ]] ; then
  COMMAND_DATABASE="db2 list db directory"
  if [[ $VERBOSE -ge 2 ]] ; then
    echo "COMMAND: $COMMAND_DATABASE"
  fi
  DB_LIST=$(${COMMAND_DATABASE} | awk '/Database alias/ {print $4}')
  if [[ $VERBOSE -ge 3 ]] ; then
    echo "RESULT:'${DB_LIST}'"
  fi

  COMMAND="
SELECT 
 DBPARTITIONNUM,
 MAX_PARTITION_MEM/1048576 AS MAX_MEM_MB,
 CURRENT_PARTITION_MEM/1048576 AS CURRENT_MEM_MB 
FROM TABLE (SYSPROC.ADMIN_GET_DBP_MEM_USAGE()) AS T;"
  CONT=true
  while read -r LINE && ${CONT} == true ; do
    DATABASE=${LINE}
    RESULT=$(db2 connect to ${DATABASE} > /dev/null ; echo ${COMMAND} | db2 +p -tx ; db2 connect reset > /dev/null)
    if [[ ${VERBOSE} -ge 3 ]] ; then
      echo "RESULT:'${RESULT}'"
    fi
    RESULT_ERROR=$(echo ${RESULT} | grep SQL)
    if [[ -z ${RESULT_ERROR} ]] ; then
      # No error for the query result, thus break the while.
      CONT=false
    fi
  done < <(printf '%s\n' "${DB_LIST}" )
  # There was not any database connection. Empty result.
  if [[ -z ${RESULT} ]] ; then
    OUTPUT="No connection to the databases in the instance at ${INSTANCE_HOME}."
    RETURN=${UNKNOWN}
  else
    while read -r LINE ; do
      NODE=$(echo ${LINE} | awk '{print $1}')
      MAX=$(echo ${LINE} | awk '{print $2}')
      CURRENT=$(echo ${LINE} | awk '{print $3}')
      if [[ ${LIMIT} == true ]] ; then
        if [[ ${CURRENT} -lt ${WARNING_THRES} ]] ; then
          OUTPUT="${OUTPUT} OK for node ${NODE}."
          if [[ ${RETURN} -gt ${OK} ]] ; then
            RETURN=${RETURN}
          else
            RETURN=${OK}
          fi
        elif [[ ${CURRENT} -lt ${CRITICAL_THRES} ]] ; then
          OUTPUT="${OUTPUT} Memory usage is increasing at node ${NODE}."
          if [[ ${RETURN} -gt ${WARNING} ]] ; then
            RETURN=${RETURN}
          else
            RETURN=${WARNING}
          fi
        else
          OUTPUT="${OUTPUT} Memory usage is critical at node ${NODE}."
          RETURN=${CRITICAL}
        fi
      fi
      if [[ ${LIMIT} == false ]] ; then
        OUTPUT="OK, memory usage is automatically."
        RETURN=${OK}
      fi
      LONG_OUTPUT="${LONG_OUTPUT} At node ${NODE} the max usage memory is ${MAX}MB and the current usage memory ${CURRENT}MB."
      PERFORMANCE="${PERFORMANCE} 'Current memory at node ${NODE}'=${CURRENT}MB"
      LONG_PERFORMANCE="${LONG_PERFORMANCE} 'Max memory at node ${NODE}'=${MAX}MB"
    done < <(printf '%s\n' "${RESULT}" )
  fi
fi

# Prints the output.
if [[ $OUTPUT == "" ]] ; then
  OUTPUT="Note: The test was not executed."
fi
# Builds the output.
echo "$OUTPUT|$PERFORMANCE
$LONG_OUTPUT|$LONG_PERFORMANCE"
# Returns the error code.
if [[ $VERBOSE -ge 2 ]] ; then
  echo "Return code: $RETURN"
fi
if [[ $TRACE == true ]] ; then
  echo -e "OUTPUT:$OUTPUT\nPERF:$PERFORMANCE\nLONG_OUT:$LONG_OUTPUT\nLONGPERF:$LONG_PERFORMANCE\nRET_CODE:$RETURN" >> $LOG
  date >> $LOG
  echo -e "<<<<<\n" >> $LOG
fi
exit $RETURN


