#! /usr/bin/env bash

###############################################################################
# Monitor DB2 with Nagios
# Copyright 2013 Andres Gomez Casanova
# https://github.com/angoca/monitor-db2-with-nagios
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

# TODO This is a template for script. The script has to be silent, it means it
# should not generate any output different to the OUTPUT variable.
#
# Here comes the documentation
#
# TODO Nagios usage.
#
# Parameters:
# -i | --instance : Home directory of the instance. Usually it is
#   /home/db2inst1
# -h | --help : Show the help of this script.
# -V | --version : Show the current version of this script.
# -v | --verbose : Execute the program in verbose mode.
#
# The exit codes are the standard for Nagios.
#
# 0 The plugin was able to check the service and it appeared to be functioning
#   properly.
# 1 The plugin was able to check the service, but it appeared to be above some
#   "warning" threshold or did not appear to be working properly.
# 2 The plugin detected that either the service was not running or it was above
#   some "critical" threshold.
# 3 Invalid command line arguments were supplied to the plugin or low-level
#   failures internal to the plugin (such as unable to fork, or open a tcp
#   socket) that prevent it from performing the specified operation.
#   Higher-level errors (such as name resolution errors, socket timeouts, etc)
#   are outside of the control of plugins and should generally NOT be reported
#   as UNKNOWN states.
#
# Author: Andres Gomez Casanova
# Version: v1.0 2013-01-18

# Flag for debugging.
#set -xv

# Version of this script.
function print_revision {
  echo v1.0 2013-01-18
}
# Function to show the help
function print_usage {
  # TODO Add arguments.
  echo "Usage: $1 { -i instanceHomeDirectory | -h | -V } [ -v ]"
}

function print_help {
  print_revision
  print_usage $1
  # Max 80 chars width.
  # TODO  Add a global description.
  echo "-i | --instance : Instance home directory. It is usually \
/home/db2inst1"
  # TODO Add arguments in detail.
  echo "-h | --help : Shows the current documentation."
  echo "-v | --verbose : Executes the script in verbose mode."
  echo "-V | --version : Shows the current version of this script."
}

# Variable to control the flow execution. Prevent Spaghetti code.
CONTINUE=true

# Nagios return codes
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
# This is the returned code.
RETURN=$UNKNOWN

# Nagios Output
# Text output 80 chars | Optional Perf Data Line 1
# Long text Line 1
# Long text Line 2 | Optional Perf Data Line 2
# Optional Perf Data Line 3
OUTPUT=
PERFORMANCE=
LONG_OUTPUT=
LONG_PERFORMANCE=

APPL_NAME=$0

if [ $# == 0 ] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

# The following requieres GNU getopt. See the following discusion.
# http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options

# TODO Add the arguments here. One char in -o, multiple char in -long.
TEMP=`getopt -o hVvi: --long help,version,verbose,instance: \
             -n $APPL_NAME -- "$@"`

if [ $? != 0 ] ; then
  print_usage $APPL_NAME
  RETURN=$UNKNOWN
  CONTINUE=false
fi

if [[ $CONTINUE == true ]] ; then
  # Note the quotes around $TEMP: they are essential!
  eval set -- "$TEMP"

  HELP=false
  VERSION=false
  VERBOSE=false
  INSTANCE_HOME=
  while true; do
    case "$1" in
      -h | --help ) HELP=true; shift ;;
      -V | --version ) VERSION=true; shift ;;
      -v | --verbose ) VERBOSE=true; shift ;;
      -i | --instance ) INSTANCE_HOME="$2"; shift 2 ;;
      # TODO Validate any new argument.
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  if [[ $CONTINUE == true && $VERBOSE == true ]] ; then
    echo "help:$HELP, version:$VERSION, verbose:$VERBOSE,
 directory:$INSTANCE_HOME"
  fi

  if [[ $CONTINUE == true && $HELP == true ]] ; then
    print_help $APPL_NAME
    RETURN=$UNKNOWN
    CONTINUE=false
  fi

  if [[ $CONTINUE == true && $VERSION == true ]] ; then
    print_revision $APPL_NAME
    RETURN=$UNKNOWN
    CONTINUE=false
  fi

  if [[ $CONTINUE == true && $INSTANCE_HOME == "" ]] ; then
    print_usage $APPL_NAME
    RETURN=$UNKNOWN
    CONTINUE=false
  fi

  if [[ $CONTINUE == true ]] ; then

    # Trims the characters.
    INSTANCE_HOME=`echo $INSTANCE_HOME | awk '{print $1}'`

    if [[ -d $INSTANCE_HOME && -e $INSTANCE_HOME/sqllib/db2profile ]] ; then
      # Load the DB2 profile.
      . $INSTANCE_HOME/sqllib/db2profile

      # TODO add the logic
    else
      OUTPUT="DB2 - Instance directory is invalid."
      RETURN=$UNKNOWN
    fi
  fi
fi

# Prints the output.
if [[ $OUTPUT == "" ]] ; then
  OUTPUT="Note: The test was not executed."
fi
# Builds the output.
echo "$OUTPUT|$PERFORMANCE
$LONG_OUTPUT|$LONG_PERFORMANCE"
# Returns the error code.
if [[ $VERBOSE == true ]] ; then
  echo Return code: $RETURN
fi
exit $RETURN
